version: '3.8'
#version: '2.19.1'
#version: '3.3'

services:
  # Create the database service
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"

  # Create the php-apache service
  php-apache-environment:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'manlikehenry/laravel-app'
    volumes:
      - . /var/www/html/
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:ZjjV4u2lW3uYS6K6T1GCtB89srKRu17Wf1Wd2ZbHxQQ=
      APP_DEBUG: true
      APP_URL: http://13.53.89.47
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel-db
      DB_USERNAME: root
      DB_PASSWORD:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120


    ports:
      - "80:80"

  # Create phpmyadmin service to view the database in the GUI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 4000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
